// src/lib/agent/tools/quote.ts
import type {
  ToolContext,
  ToolDefinition,
  ToolExecutionResult,
} from "./index";

export function quoteTools(_ctx: ToolContext): ToolDefinition[] {
  const explainQuoteLogic: ToolDefinition = {
    spec: {
      type: "function",
      function: {
        name: "explainQuoteLogic",
        description:
          "Explain how Pace Shuttles calculates per-seat prices (base fare plus taxes and fees, with rounding), without generating a live quote.",
        parameters: {
          type: "object",
          properties: {},
          additionalProperties: false,
        },
      },
    },
    run: async (): Promise<ToolExecutionResult> => {
      const content =
        "Pace Shuttles prices are calculated per seat as an all-in amount that includes base fare, applicable taxes, and fees, then rounded up to the nearest whole currency unit. Live quotes are generated by the booking engine when you select a specific journey, date, and party size.";
      return { messages: [{ role: "assistant", content }] };
    },
  };

  return [explainQuoteLogic];
}
